name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release and Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build package
        run: npm run build

      - name: Extract version from tag
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Get previous tag
        id: previous_tag
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          PREVIOUS_TAG=$(git tag --sort=-creatordate | grep -A 1 "^${CURRENT_TAG}$" | tail -1)
          if [ -z "$PREVIOUS_TAG" ] || [ "$PREVIOUS_TAG" = "$CURRENT_TAG" ]; then
            echo "tag=" >> $GITHUB_OUTPUT
            echo "has_previous=false" >> $GITHUB_OUTPUT
          else
            echo "tag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT
            echo "has_previous=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate release body
        id: release_body
        run: |
          BODY="## Changes in v${{ steps.version.outputs.version }}

          "
          if [ "${{ steps.previous_tag.outputs.has_previous }}" = "true" ]; then
            BODY="${BODY}See [CHANGELOG](https://github.com/${{ github.repository }}/compare/${{ steps.previous_tag.outputs.tag }}...${{ github.ref_name }}) for details."
          else
            BODY="${BODY}Initial release."
          fi
          BODY="${BODY}

          ## Installation

          \`\`\`bash
          npm install flowerpassword.js@${{ steps.version.outputs.version }}
          \`\`\`"
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release v${{ steps.version.outputs.version }}
          body: ${{ steps.release_body.outputs.body }}
          draft: false
          prerelease: false
          files: |
            dist/**/*

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
